/**
 * Generated by anjay_codegen.py on 2022-11-23 13:34:25
 *
 * LwM2M Object: Digital Output
 * ID: 3201, URN: urn:oma:lwm2m:ext:3201, Optional, Multiple
 *
 * Generic digital output for non-specific actuators
 */
#include <assert.h>
#include <stdbool.h>

#include <anjay/anjay.h>
#include <avsystem/commons/avs_defs.h>
#include <avsystem/commons/avs_list.h>
#include <avsystem/commons/avs_memory.h>

#include "objects/objects.h"
#include "driver/gpio.h"

/**
 * Digital Output State: RW, Single, Mandatory
 * type: boolean, range: N/A, unit: N/A
 * The current state of a digital output.
 */
#define RID_DIGITAL_OUTPUT_STATE 5550

typedef struct digital_output_instance_struct {
    anjay_iid_t iid;
    bool out_state;
    // TODO: instance state
} digital_output_instance_t;

typedef struct digital_output_object_struct {
    const anjay_dm_object_def_t *def;
    AVS_LIST(digital_output_instance_t) instances;

    // TODO: object state
} digital_output_object_t;

static inline digital_output_object_t *
get_obj(const anjay_dm_object_def_t *const *obj_ptr) {
    assert(obj_ptr);
    return AVS_CONTAINER_OF(obj_ptr, digital_output_object_t, def);
}

static digital_output_instance_t *find_instance(const digital_output_object_t *obj,
                                                anjay_iid_t iid) {
    AVS_LIST(digital_output_instance_t) it;
    AVS_LIST_FOREACH(it, obj->instances) {
        if (it->iid == iid) {
            return it;
        } else if (it->iid > iid) {
            break;
        }
    }

    return NULL;
}

static int list_instances(anjay_t *anjay,
                          const anjay_dm_object_def_t *const *obj_ptr,
                          anjay_dm_list_ctx_t *ctx) {
    (void) anjay;

    AVS_LIST(digital_output_instance_t) it;
    AVS_LIST_FOREACH(it, get_obj(obj_ptr)->instances) {
        anjay_dm_emit(ctx, it->iid);
    }

    return 0;
}

static int init_instance(digital_output_instance_t *inst, anjay_iid_t iid) {
    assert(iid != ANJAY_ID_INVALID);

    inst->iid = iid;
    // TODO: instance init
    inst->out_state=0;
    // TODO: return 0 on success, negative value on failure
    return 0;
}

static void release_instance(digital_output_instance_t *inst) {
    // TODO: instance cleanup
    (void) inst;
}

static digital_output_instance_t *
add_instance(digital_output_object_t *obj, anjay_iid_t iid) {
    assert(find_instance(obj, iid) == NULL);

    AVS_LIST(digital_output_instance_t) created =
            AVS_LIST_NEW_ELEMENT(digital_output_instance_t);
    if (!created) {
        return NULL;
    }

    int result = init_instance(created, iid);
    if (result) {
        AVS_LIST_CLEAR(&created);
        return NULL;
    }

    AVS_LIST(digital_output_instance_t) *ptr;
    AVS_LIST_FOREACH_PTR(ptr, &obj->instances) {
        if ((*ptr)->iid > created->iid) {
            break;
        }
    }

    AVS_LIST_INSERT(ptr, created);
    return created;
}

static int instance_create(anjay_t *anjay,
                           const anjay_dm_object_def_t *const *obj_ptr,
                           anjay_iid_t iid) {
    (void) anjay;
    digital_output_object_t *obj = get_obj(obj_ptr);
    assert(obj);

    return add_instance(obj, iid) ? 0 : ANJAY_ERR_INTERNAL;
}

static int instance_remove(anjay_t *anjay,
                           const anjay_dm_object_def_t *const *obj_ptr,
                           anjay_iid_t iid) {
    (void) anjay;
    digital_output_object_t *obj = get_obj(obj_ptr);
    assert(obj);

    AVS_LIST(digital_output_instance_t) *it;
    AVS_LIST_FOREACH_PTR(it, &obj->instances) {
        if ((*it)->iid == iid) {
            release_instance(*it);
            AVS_LIST_DELETE(it);
            return 0;
        } else if ((*it)->iid > iid) {
            break;
        }
    }

    assert(0);
    return ANJAY_ERR_NOT_FOUND;
}

static int instance_reset(anjay_t *anjay,
                          const anjay_dm_object_def_t *const *obj_ptr,
                          anjay_iid_t iid) {
    (void) anjay;

    digital_output_object_t *obj = get_obj(obj_ptr);
    assert(obj);
    digital_output_instance_t *inst = find_instance(obj, iid);
    assert(inst);
    inst->out_state=0;
    // TODO: instance reset
    return 0;
}

static int list_resources(anjay_t *anjay,
                          const anjay_dm_object_def_t *const *obj_ptr,
                          anjay_iid_t iid,
                          anjay_dm_resource_list_ctx_t *ctx) {
    (void) anjay;
    (void) obj_ptr;
    (void) iid;

    anjay_dm_emit_res(ctx, RID_DIGITAL_OUTPUT_STATE,
                      ANJAY_DM_RES_RW, ANJAY_DM_RES_PRESENT);
    return 0;
}

static int resource_read(anjay_t *anjay,
                         const anjay_dm_object_def_t *const *obj_ptr,
                         anjay_iid_t iid,
                         anjay_rid_t rid,
                         anjay_riid_t riid,
                         anjay_output_ctx_t *ctx) {
    (void) anjay;

    digital_output_object_t *obj = get_obj(obj_ptr);
    assert(obj);
    digital_output_instance_t *inst = find_instance(obj, iid);
    assert(inst);

    switch (rid) {
    case RID_DIGITAL_OUTPUT_STATE:
        assert(riid == ANJAY_ID_INVALID);
        return anjay_ret_bool(ctx, inst->out_state); // TODO

    default:
        return ANJAY_ERR_METHOD_NOT_ALLOWED;
    }
}

static int resource_write(anjay_t *anjay,
                          const anjay_dm_object_def_t *const *obj_ptr,
                          anjay_iid_t iid,
                          anjay_rid_t rid,
                          anjay_riid_t riid,
                          anjay_input_ctx_t *ctx) {
    (void) anjay;

    digital_output_object_t *obj = get_obj(obj_ptr);
    assert(obj);
    digital_output_instance_t *inst = find_instance(obj, iid);
    assert(inst);

    switch (rid) {
    case RID_DIGITAL_OUTPUT_STATE: {
        assert(riid == ANJAY_ID_INVALID);
        anjay_get_bool(ctx, &inst->out_state); // TODO
        return gpio_set_level(GPIO_NUM_17,inst->out_state);
    }

    default:
        return ANJAY_ERR_METHOD_NOT_ALLOWED;
    }
}

static const anjay_dm_object_def_t OBJ_DEF = {
    .oid = 3201,
    .handlers = {
        .list_instances = list_instances,
        .instance_create = instance_create,
        .instance_remove = instance_remove,
        .instance_reset = instance_reset,

        .list_resources = list_resources,
        .resource_read = resource_read,
        .resource_write = resource_write,

        // TODO: implement these if transactional write/create is required
        .transaction_begin = anjay_dm_transaction_NOOP,
        .transaction_validate = anjay_dm_transaction_NOOP,
        .transaction_commit = anjay_dm_transaction_NOOP,
        .transaction_rollback = anjay_dm_transaction_NOOP
    }
};

const anjay_dm_object_def_t **digital_output_object_create(void) {
    digital_output_object_t *obj = (digital_output_object_t *) avs_calloc(1, sizeof(digital_output_object_t));
    if (!obj) {
        return NULL;
    }
    obj->def = &OBJ_DEF;
    digital_output_instance_t *inst=add_instance(obj,0);

    gpio_config_t io_conf = {};
    //disable interrupt
    io_conf.intr_type = GPIO_INTR_DISABLE;
    //set as output mode
    io_conf.mode = GPIO_MODE_OUTPUT;
    //bit mask of the pins that you want to set,e.g.GPIO18/19
    io_conf.pin_bit_mask = BIT64(17);
    //disable pull-down mode
    io_conf.pull_down_en = 0;
    //disable pull-up mode
    io_conf.pull_up_en = 0;
    //configure GPIO with the given settings
    gpio_config(&io_conf);

    return &obj->def;
}

void digital_output_object_release(const anjay_dm_object_def_t **def) {
    if (def) {
        digital_output_object_t *obj = get_obj(def);
        AVS_LIST_CLEAR(&obj->instances) {
            release_instance(obj->instances);
        }

        // TODO: object cleanup

        avs_free(obj);
    }
}
